[package]
name = "svpn"
version = "0.1.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
edition = "2018"

[dependencies]
# r0 = "0.2.2"
# riscv = "0.3.0"
# spin = { version = "0.4.10", default-features = false }